### ISSUE TITLE
Cannot illuminate HEAT back up sight on M1IP

### ISSUE THREAD

**Issue by JoeThe-Pirate** [RadianSimulations/ghpc-feedback#125] opened 2022-10-23 19:43 UTC
**Describe the bug**

When using the back up/aux sight on the M1IP and firing HEAT, the reticle cannot be illuminated. If the reticle for APFSDS is illuminated and the next round loaded is HEAT, illumination will turn off. This only impacts the M1IP. M1, M60TTS, and M60 RISE do not have this bug. Appears in all maps/missions tried

**To Reproduce**

1. Use M1IP aux/back up sight
2. Load HEAT
3. use 'I' to illuminate reticle

**Expected Behavior**

Reticle should illuminate for HEAT like other NATO aux sights

**Screenshots**

N/A

**Sources**

N/A
**Desktop (Please complete the following information):**

-     OS: windows 10
-     Game Version steam version, 20220830.1
-     CPU: AMD Ryzen 7 2700X
-     GPU: NVIDIA GeForce RTX 3060
-     RAM: 16GB

**Additional context**

N/A

**Comment by JoshBusuito** [comment] 2022-10-24 13:24
Duplicate of #90

**Closed by JoshBusuito** 2022-10-24 13:24 UTC
Labels: Bug, Duplicate
