### ISSUE TITLE
M2 Bradley Main Sight Reticle Missing

### ISSUE THREAD

**Issue by OpaqueArc** [RadianSimulations/ghpc-feedback#94] opened 2022-09-07 07:39 UTC
**Describe the bug**

When the game is loaded, the M2 Bradley may have its main sight reticle for 25mm cannon missing in both zoomed in/out .

**To Reproduce**

See above, it is almost 100% reproducible in campaign, not tested in range

**Expected Behavior**

25mm cannon has its reticle correctly displayed.

**Screenshots**

N/A

**Sources**

N/A

**Desktop (Please complete the following information):**

 - OS: Windows 10
 - Game Version 20220830 Steam EA

**Additional context**

As for now, using [] or F to switch weapons would correctly load the reticle.

**Comment by Eviscerator46** [comment] 2022-09-07 08:42
that's how the M2 sight is supposed to work, in thermal sight when zoom out no matter what weapon is selected you will only see the TOW reticle. And in day sight you will only see the canon reticle if you have it selected or using the coax, it disappears when using TOWs

**Comment by TeyKey1** [comment] 2022-09-07 13:29
The bug is about having it missing when zoomed in as well so that is indeed not intended. I can reproduce this as well in campaign mode but not in regular missions.

**Comment by blake-bracerstudios** [comment] 2022-09-11 01:25
Certain campaign missions will be removed as their set up pipeline has not been updated with other work we've done. This error is a symptom of those missions. Will close this issue once that's finished.

**Comment by JoshBusuito** [comment] 2022-09-17 21:25
Fixed by RadianSimulations/GHPC-vertical#961

**Closed by JoshBusuito** 2022-09-17 21:25 UTC
Labels: Bug
