### ISSUE TITLE
Loader makes false 'black on ___' callout during ammo switch

### ISSUE THREAD

**Issue by Eddie894** [RadianSimulations/ghpc-feedback#286] opened 2024-07-19 06:28 UTC
**Describe the bug**

Only applicable to the Abrams and M60 tanks,

While the second-to-last available round of either ammo type is loaded, ordering a switch to the other ammo type and then firing, will cause the loader to call 'Black on-' the newly loaded ammo type, regardless of whether the ready rack is depleted of it or not.

No mods installed.

1st example:
Ensure plenty HEAT available in ready rack (default stock satisfactory)
Load FIN (default)
Fire FIN until 1 FIN remains in the ready rack AND 1 FIN loaded in the tube (2 total)
Order load HEAT
Fire
Loader calls: 'Black on HEAT!'

2nd example:
Ensure plenty FIN available in ready rack (default stock satisfactory)
Order load HEAT
Fire
Continue to fire HEAT until 1 HEAT remains in the ready rack AND 1 HEAT loaded in the tube (2 total)
Order load FIN
Fire
Loader calls: 'Black on SABOT!'

Loader should not be calling 'Black on ___' at all as one piece of the previous ammo type remains in the rack, and plenty remains of the next type. Loader should only be shouting 'SABOT/HEAT up!'.

Of course, the exception would be when there is only one piece of the second ammo type remaining anyway, as the callout by the loader would then be correct.

OS: Windows 11

Game Version: 20240710.1

https://github.com/user-attachments/assets/b4062a15-14b2-4ad5-b69b-7d01c0892307

**Comment by JoshBusuito** [comment] 2024-07-19 07:34
Duplicate of #58

**Closed as completed by JoshBusuito** 2024-07-19 07:34 UTC
Labels: Bug
