### ISSUE TITLE
Cannot un-illuminate M2 reticle

### ISSUE THREAD

**Issue by JoeThe-Pirate** [RadianSimulations/ghpc-feedback#123] opened 2022-10-23 19:21 UTC
**Describe the bug**

Illuminating the reticent for the M2 Bradley is permanent. Pressing 'I' again does not turn off illumination. Swapping views or vehicles does not rectify. Appears in proving grounds, instant action, and campaign. 

**To Reproduce**

Press 'I' while in optics view on M2, no other prerequisites known

**Expected Behavior**

Reticle will un-illluminate after pressing 'I' again similar to BRDM, T72, etc

**Screenshots**

N/A

**Sources**
N/A

**Desktop (Please complete the following information):**

 - OS: windows 10
 - Game Version steam version, 20220830.1
 - CPU: AMD Ryzen 7 2700X
 - GPU: NVIDIA GeForce RTX 3060
 - RAM: 16GB

**Additional context**
N/A

**Comment by JoshBusuito** [comment] 2022-10-24 13:21
Duplicate of #88

**Closed by JoshBusuito** 2022-10-24 13:21 UTC
Labels: Bug, Duplicate
