### ISSUE TITLE
Vegetation Memory Access Error

### ISSUE THREAD

**Issue by Alexbay218** [RadianSimulations/ghpc-feedback#153] opened 2023-02-03 04:20 UTC
**Describe the bug**

I know its been reported already, but I've here to submit another ticket to help with data collection. The crash associated with the specific log occurred at the beginning of Incredible Intuition. Curiously, only happens when using gunner sights.

Related to #140

**To Reproduce**

1. Instant
2. Fulda Gap - Fulda Outskirts
3. Incredible Intuition
4. Start
5. Press SHIFT key for gunners sights
6. Crash occurs after a small delay

**Expected Behavior**

Not crashing is preferred.

**Screenshots**

Current video settings and game version:

![image](https://user-images.githubusercontent.com/9091117/216509259-b00f19dc-edb3-4f69-8d64-637afe10419a.png)

System Info from dxdiag:

![image](https://user-images.githubusercontent.com/9091117/216509961-07a9bbe4-8bcb-42ab-91ff-abb6c2528dbf.png)

GPU Info from GPU-Z:

![image](https://user-images.githubusercontent.com/9091117/216510240-410f48cb-bbb6-4219-a1d8-98c3b9048121.png)

**Log**

[Player.log](https://github.com/RadianSimulations/ghpc-feedback/files/10575409/Player.log)

**Comment by Alexbay218** [comment] 2023-02-03 19:34
Also happened with M1 on Bold Limit
[Player-prev.log](https://github.com/RadianSimulations/ghpc-feedback/files/10582124/Player-prev.log)

**Comment by Alexbay218** [comment] 2023-02-03 22:25
Is there a debug build I can run? The log file doesn't seem particularly helpful

**Comment by blake-bracerstudios** [comment] 2023-04-13 02:36
There isn't a debug build available, as we're aware of the issue in a dependency and are taking steps to vet replacements. But this is a duplicate of #140 so closing this.

**Closed by blake-bracerstudios** 2023-04-13 02:36 UTC
Labels: Bug, Duplicate
