### ISSUE TITLE
Crash on Raid Praying Mantis

### ISSUE THREAD

**Issue by Nico-but-with-a-sword** [RadianSimulations/ghpc-feedback#129] opened 2022-10-31 11:39 UTC
Game crashes on the Praying Mantis Raid as PACT forces once past the first M113 and engaging the ATGM and objectives on Husky

Campaign mode 
Call Artillery on objective Husky
Get to the south of objective Husky
Start taking potshots and taking fire
Game crashes

See attached logs: 

[Player.log](https://github.com/RadianSimulations/ghpc-feedback/files/9900693/Player.log)
[Player-prev.log](https://github.com/RadianSimulations/ghpc-feedback/files/9900694/Player-prev.log)

**Comment by blake-bracerstudios** [comment] 2022-11-29 21:55
Closing as a duplicate of #140

**Closed by blake-bracerstudios** 2022-11-29 21:55 UTC
Labels: Bug, Duplicate
