### ISSUE TITLE
T-55A reverse problem

### ISSUE THREAD

**Issue by Barleyman** [RadianSimulations/ghpc-feedback#164] opened 2023-03-28 00:00 UTC
**Describe the bug**

T-55A does bunny-hopping behaviour while reversing, similar to an inexperienced driver getting into grips with the clutch. This doesn't help on shoot'n'scoot and T-55A is at a big disadvantage already. 

**To Reproduce**

1. Start "IFV Incident" mission. 
2. Reverse. 

**Expected Behavior**

Steadily back up, this works in the Grafenwoehr tank range, but not in the scenario mentioned or other T-55A scenarios. 

**Desktop (Please complete the following information):**

Win11 20230228.2

**Additional context**

There's bug back from 2021 on this, but this particular mission shows the problem right away.

**Comment by JoshBusuito** [comment] 2023-03-28 00:22
Duplicate of #34

**Closed by JoshBusuito** 2023-03-28 00:22 UTC
Labels: Bug
